const PROCESS_PAYMENT = 'PROCESS_PAYMENT';
const CANCEL_RESERVATION_REQUEST = 'CANCEL_RESERVATION_REQUEST';
const GENERATE_TICKET_REQUEST = 'GENERATE_TICKET_REQUEST';

module.exports = {
    PROCESS_PAYMENT,
    CANCEL_RESERVATION_REQUEST,
    GENERATE_TICKET_REQUEST
};
