services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # mongo-movie:
  #   image: mongo:6
  #   container_name: mongo_movie
  #   ports:
  #     - "27018:27017"
  #   volumes:
  #     - mongo_movie_data:/data/db

  # mongo-reservation:
  #   image: mongo:6
  #   container_name: mongo_reservation
  #   ports:
  #     - "27019:27017"
  #   volumes:
  #     - mongo_reservation_data:/data/db

  event-sender:
    build:
      context: ./EventSender
    container_name: eventsender
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"

  # reservation-service:
  #   build:
  #     context: ./ReservationService
  #   container_name: reservationservice
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   ports:
  #     - "3001:3001"

  # movie-service:
  #   build:
  #     context: ./MovieService
  #   container_name: movieservice
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   ports:
  #     - "3002:3002"

  payment-service:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    container_name: paymentService
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3003:3003"

  ticket-service:
    build:
      context: .
      dockerfile: TicketService/Dockerfile
    container_name: ticketService
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3004:3004"

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    container_name: notificationService
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3005:3005"

# volumes:
#   mongo_movie_data:
#   mongo_reservation_data: